sslCert: /aa/bb
dubbo:
  registry:
    address: spring-cloud://localhost:8848

  protocols:
    dubbo:
      name: dubbo
      port: -1
      server: netty
      sslEnabled: false
    rest:
      name: rest
      port: -1
      server: netty
      sslEnabled: false

  cloud:
    subscribed-services: none
  scan:
    base-packages: com.xinwen.payment.service

debug: true


spring:
  application:
    name: paymentService
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        #namespace: 5ee9b536-dea2-4377-b7d6-c1b62eaa65b7
        port: 8848
    sentinel:
      transport:
        port: 8721
        dashboard: localhost:8989
      # 设置Sentinel Nacos数据源配置
      datasource:
        #其中flow是数据源名，可以自行随意修改
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            # 配置后报错提示：Type 'com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties' has no property 'rule-type' ， 以为哪里配置错了或版本不对， 最后发现忽略即可， 项目可正常启动
            rule-type: flow
            #在nacos配置列表中添加配置paymentService-flow-rules
            #nacos中的规则会自动同步到sentinel控制台的流控规则中
            # app: 服务名称， resource:请求方法或地址, limitApp: 流控针对的调用来源，若为 default 则不区分调用来源
            # grade: 限流类型 0－按并发数量来限流， 1－按QPS来限流, strategy: 调用关系限流策略
            # controlBehavior: 流量控制效果（直接拒绝、Warm Up、匀速排队）, clusterMode: 是否应用于集群模式
            #            [
            #                {
            #                    "app":"autoee-busi-dubbo-sentinel-nacos-provider",
            #                    "resource":"com.autoee.busi.service.EchoService:echo(java.lang.String)",
            #                    "limitApp":"default",
            #                    "grade":1,
            #                    "count":1,
            #                    "strategy":0,
            #                    "controlBehavior":0,
            #                    "clusterMode":false
            #                }
            #            ]

          #        degrade:
          #          nacos:
          #            server-addr: localhost:8848
          #            dataId: ${spring.application.name}-degrade-rules
          #            groupId: SENTINEL_GROUP
          #            rule-type: degrade
          #        system:
          #          nacos:
          #            server-addr: localhost:8848
          #            dataId: ${spring.application.name}-system-rules
          #            groupId: SENTINEL_GROUP
          #            rule-type: system
          #        authority:
          #          nacos:
          #            server-addr: localhost:8848
          #            dataId: ${spring.application.name}-authority-rules
          #            groupId: SENTINEL_GROUP
          #            rule-type: authority
          #        param-flow:
          #          nacos:
          #            server-addr: localhost:8848
          #            dataId: ${spring.application.name}-param-flow-rules
          #            groupId: SENTINEL_GROUP
          #            rule-type: param-flow


#
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    message-timeout: 5
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      rate: 1
